PUBLIC FUN TRANSPOSE_MATRIX(IN _ARR)
{
  IF (RANK (_ARR) != 2) ABORT();
  _COLS = SIZE(_ARR, 0);
  _ROWS = SIZE(_ARR, 1);
  _SZ = _COLS*_ROWS;

  _IDX = (0 : _COLS-1) : _SZ-1 : _COLS;
  RETURN (SET_RANGE(_ROWS, _COLS, MAP(_ARR, _IDX)));
}
