c
c It is confusing to see two functions of the same name, such as "murrv", in
c the same library.  What is occurring is that although the names are the same
c in the source files, this file is compiled without name mangling and the other
c file is mangled.   Thus this function compiles to "murrv" and the other
c file compiles to "murrv_" (trailing underscore).  The same applies to the
c other functions.
c
c This file was initially generated by a program that used Lex to scan the 
c actual functions and extract the information to write these interface routines.
c
      subroutine  murrv(argc,argv)
      integer argc,argv(*)
      call murrv_(
     + %val(argv(1)),
     + %val(argv(2)),
     + %val(argv(3)),
     + %val(argv(4)),
     + %val(argv(5)),
     + %val(argv(6)),
     + %val(argv(7)),
     + %val(argv(8)),
     + %val(argv(9)))
      end
c*********************************************Arguments:9
      subroutine  mrrrr(argc,argv)
      integer argc,argv(*)
      call mrrrr_(
     + %val(argv(1)),
     + %val(argv(2)),
     + %val(argv(3)),
     + %val(argv(4)),
     + %val(argv(5)),
     + %val(argv(6)),
     + %val(argv(7)),
     + %val(argv(8)),
     + %val(argv(9)),
     + %val(argv(10)),
     + %val(argv(11)),
     + %val(argv(12)))
      end
c*********************************************Arguments:12
      subroutine  muzrv(argc,argv)
      integer argc,argv(*)
      call muzrv_(
     + %val(argv(1)),
     + %val(argv(2)),
     + %val(argv(3)),
     + %val(argv(4)),
     + %val(argv(5)),
     + %val(argv(6)),
     + %val(argv(7)),
     + %val(argv(8)),
     + %val(argv(9)))
      end
c*********************************************Arguments:9
      subroutine  mrrzz(argc,argv)
      integer argc,argv(*)
      call mrrzz_(
     + %val(argv(1)),
     + %val(argv(2)),
     + %val(argv(3)),
     + %val(argv(4)),
     + %val(argv(5)),
     + %val(argv(6)),
     + %val(argv(7)),
     + %val(argv(8)),
     + %val(argv(9)),
     + %val(argv(10)),
     + %val(argv(11)),
     + %val(argv(12)))
      end
c*********************************************Arguments:12
